
base.url=https://api.etrade.com
sandbox.base.url=https://apisb.etrade.com


#Define your E*Trade API consumer key and secret keys here. Or set as JVM parameters
#-Dconsumer.key
consumer.key=
#-Dconsumer.secret
consumer.secret=